services:
  plotterfun-node-editor:
    image: ${IMAGE_REF:-docker.io/andpra70/plotterfun-node-editor:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plotterfun-node-editor
    restart: unless-stopped
    ports:
      - "8080:80"
