export interface NodePaletteItem {
  type: string;
  category: "io" | "basic" | "focus" | "colors" | "art" | "graphic" | "plotter" | "ai" | "svg";
  glyph: string;
  shortLabel: string;
  tooltip: string;
}

export const nodePalette: NodePaletteItem[] = [
  { type: "input/image", category: "io", glyph: "IN", shortLabel: "Image", tooltip: "INPUT: carica o trascina un'immagine." },
  { type: "input/webcam", category: "io", glyph: "CAM", shortLabel: "Webcam", tooltip: "WEBCAM: mostra il live video e cattura con Grab." },
  { type: "tools/colors/invert", category: "colors", glyph: "INV", shortLabel: "Invert", tooltip: "INVERT: inverte i colori dell'immagine." },
  { type: "tools/colors/grayscale", category: "colors", glyph: "GRY", shortLabel: "Gray", tooltip: "GRAYSCALE: converte l'immagine in scala di grigi." },
  { type: "tools/colors/threshold", category: "colors", glyph: "THR", shortLabel: "Thresh", tooltip: "THRESHOLD: binarizza l'immagine con una soglia." },
  { type: "tools/colors/halftoning", category: "colors", glyph: "HLF", shortLabel: "Halftone", tooltip: "HALFTONING: converte l'immagine in mezzitoni con tipi Ordered, Floyd-Steinberg, Atkinson o Density pattern e controlli di soglia." },
  { type: "tools/colors/histogram", category: "colors", glyph: "HST", shortLabel: "Hist", tooltip: "HISTOGRAM: mostra istogramma dell'immagine con modalita RGB, HSV o scala di grigi." },
  { type: "tools/colors/levels", category: "colors", glyph: "LVL", shortLabel: "Levels", tooltip: "LEVELS: regola livelli con controlli in/out e gamma su RGB, HSV, Gray o Alpha." },
  { type: "tools/focus/blur", category: "focus", glyph: "BLR", shortLabel: "Blur", tooltip: "BLUR: sfoca l'immagine in ingresso." },
  { type: "tools/focus/sharpen", category: "focus", glyph: "SHP", shortLabel: "Sharpen", tooltip: "SHARPEN: aumenta nitidezza con preset e amount." },
  { type: "tools/focus/sobel", category: "focus", glyph: "SBL", shortLabel: "Sobel", tooltip: "SOBEL: edge detection con modalita magnitude/horizontal/vertical/threshold." },
  { type: "tools/basic/rotatePanZoom", category: "basic", glyph: "RPZ", shortLabel: "RPZ", tooltip: "ROTATE PAN ZOOM: ruota, zooma e croppa con pan sliders e bird-eye della zona di crop." },
  { type: "tools/basic/scale", category: "basic", glyph: "SCL", shortLabel: "Scale", tooltip: "SCALE: ridimensiona l'immagine in percentuale." },
  { type: "tools/basic/rotate", category: "basic", glyph: "ROT", shortLabel: "Rotate", tooltip: "ROTATE: ruota l'immagine dell'angolo impostato." },
  { type: "tools/colors/brightness-contrast", category: "colors", glyph: "B/C", shortLabel: "Bri/Con", tooltip: "BRIGHTNESS/CONTRAST: regola luminosita e contrasto." },
  { type: "tools/colors/rgb-split", category: "colors", glyph: "RGB", shortLabel: "RGB Split", tooltip: "RGB SPLIT: separa l'immagine in 3 uscite (R,G,B)." },
  { type: "tools/colors/cmyk-split", category: "colors", glyph: "CMYK", shortLabel: "CMYK Split", tooltip: "CMYK SPLIT: separa l'immagine in 4 uscite (C,M,Y,K)." },
  { type: "tools/colors/rgb-combine", category: "colors", glyph: "RGB+", shortLabel: "RGB Join", tooltip: "RGB COMBINE: ricompone immagine colore da 3 canali R,G,B." },
  { type: "tools/colors/cmyk-combine", category: "colors", glyph: "CMY+", shortLabel: "CMYK Join", tooltip: "CMYK COMBINE: ricompone immagine colore da 4 canali C,M,Y,K." },
  { type: "tools/colors/quantize", category: "colors", glyph: "QNT", shortLabel: "Quant", tooltip: "QUANTIZE: riduce la palette con PnnQuant, con output immagine e palette." },
  { type: "tools/colors/blend", category: "colors", glyph: "B2", shortLabel: "Blend", tooltip: "BLEND: miscela due immagini con modalita, alpha, offset e scala." },
  { type: "tools/colors/layers", category: "colors", glyph: "LYR", shortLabel: "Layers", tooltip: "LAYERS: blend in stack di N immagini con alpha e blend mode per layer." },
  { type: "tools/art/oil", category: "art", glyph: "OIL", shortLabel: "Oil", tooltip: "OIL: effetto pittura a olio con parametri radius e intensity." },
  { type: "tools/art/oil2", category: "art", glyph: "O2", shortLabel: "Oil2", tooltip: "OIL2: portrait painter a pennellate curve multi-layer (stile p5), con output raster + SVG." },
  { type: "tools/art/oil3", category: "art", glyph: "O3", shortLabel: "Oil3", tooltip: "OIL3: variante painter basata su oilp5.2, con step/rotazione/dettagli parametrizzabili (output raster + SVG)." },
  { type: "tools/art/watercolour", category: "art", glyph: "WTR", shortLabel: "Water", tooltip: "WATERCOLOUR: simulazione acquerello fedele con wash, diffusione colore, trasparenza e densita pennellata (output raster + SVG)." },
  { type: "tools/art/lines", category: "art", glyph: "LIN", shortLabel: "Lines", tooltip: "LINES: field di linee orizzontali deformate dalla luminanza immagine, con controlli su interlinea, punti, ampiezza e zoom/pan (output raster + SVG)." },
  { type: "tools/art/dots", category: "art", glyph: "DOT", shortLabel: "Dots", tooltip: "DOTS: griglia di cerchi colorati campionati dall'immagine (stile p5 dots), con controllo tile/diametro/sfondo (output raster + SVG)." },
  { type: "tools/art/asciify", category: "art", glyph: "ASC", shortLabel: "Ascii", tooltip: "ASCIIFY: converte immagine in ASCII art con output raster, SVG e testo." },
  { type: "tools/art/sketch", category: "art", glyph: "SKT", shortLabel: "Sketch", tooltip: "SKETCH: tratteggio progressivo basato sulle aree piu scure (darkest squiggles), ottimizzato con preset FAST/NORMAL/SLOW e output raster+SVG." },
  { type: "tools/graphic/sketch", category: "graphic", glyph: "GSK", shortLabel: "GSketch", tooltip: "GRAPHIC SKETCH: sketch a matita con linea continua iterativa, convergenza su errore, preset FAST/MEDIUM/SLOW e stop per stagnazione errore (output raster+SVG)." },
  { type: "tools/graphic/hatching", category: "graphic", glyph: "HAT", shortLabel: "Hatching", tooltip: "GRAPHIC HATCHING: hatching adattivo guidato da tono residuo e orientamento locale dei gradienti, con preset FAST/NORMAL/SLOW e output raster+SVG ad alta fedelta." },
  { type: "tools/graphic/scumbling", category: "graphic", glyph: "SCU", shortLabel: "Scumble", tooltip: "GRAPHIC SCUMBLING: tratteggio a micro-loop/circoli sovrapposti da manuale grafico, guidato da tono residuo e orientamento locale con preset FAST/NORMAL/SLOW e output raster+SVG super fedele." },
  { type: "tools/graphic/crosshatiching", category: "graphic", glyph: "XHT", shortLabel: "CrossHat", tooltip: "GRAPHIC CROSSHATICHING: crosshatching multi-angolo ad alta fedelta guidato da tono e gradienti, con modalita manuale (wobble/jitter/break/pressure), output raster+SVG." },
  { type: "tools/graphic/pencil", category: "graphic", glyph: "BIC", shortLabel: "Pencil", tooltip: "GRAPHIC PENCIL: ritratto single-line stile penna bic con un unico tratto continuo (campionamento scuro + routing + ottimizzazione), output raster+SVG." },
  { type: "tools/graphic/scribbling", category: "graphic", glyph: "SCR", shortLabel: "Scribble", tooltip: "GRAPHIC SCRIBBLING: inchiostrazione a scarabocchio guidata da tono e campo di gradienti, con resa manuale a china/penna e output raster+SVG." },
  { type: "tools/graphic/tonalShading", category: "graphic", glyph: "TSH", shortLabel: "Tonal", tooltip: "GRAPHIC TONAL SHADING: tratteggio tonale professionale multi-direzione guidato da tono e gradienti locali, con output raster+SVG ad alta fedelta." },
  { type: "tools/art/delanoy", category: "art", glyph: "DEL", shortLabel: "Delanoy", tooltip: "DELANOY: triangolazione Delaunay su griglia e render wireframe (output raster+SVG)." },
  { type: "tools/art/delanoy2", category: "art", glyph: "DE2", shortLabel: "Delanoy2", tooltip: "DELANOY2: triangolazione Delaunay e cerchi per triangolo (output raster+SVG)." },
  { type: "tools/art/linefy", category: "art", glyph: "LNF", shortLabel: "Linefy", tooltip: "LINEFY: line-art progressivo in stile linify con preset FAST/NORMAL/SLOW e output raster+SVG." },
  { type: "tools/art/linefy2", category: "art", glyph: "LN2", shortLabel: "Linefy2", tooltip: "LINEFY2: variante superveloce canvas-based (senza Bresenham) con preset FAST/NORMAL/SLOW e output raster+SVG." },
  { type: "tools/art/griddot", category: "art", glyph: "GRD", shortLabel: "GridDot", tooltip: "GRIDDOT: halftone a griglia di cerchi basato su luminanza, con preset FAST/NORMAL/SLOW e output raster+SVG." },
  { type: "tools/art/stipple", category: "art", glyph: "STP", shortLabel: "Stipple", tooltip: "STIPPLE: puntinismo adattivo con rilassamento, output raster + SVG e controlli su densita, raggio e seed." },
  { type: "tools/art/vectorize", category: "art", glyph: "SVG", shortLabel: "Vector", tooltip: "VECTORIZE: vettorizza l'immagine con ImageTracer e produce raster+SVG." },
  { type: "tools/art/marching", category: "art", glyph: "ISO", shortLabel: "Marching", tooltip: "MARCHING: estrae superfici di livello dall'immagine (output raster + SVG) con preset Fast/Quality." },
  { type: "tools/art/boldini", category: "art", glyph: "BOL", shortLabel: "Boldini", tooltip: "BOLDINI: pittura stilizzata a pennellate multi-layer (base/intermedie/dettagli) da immagine input." },
  { type: "tools/art/seargeant", category: "art", glyph: "SRG", shortLabel: "Searg", tooltip: "SEARGEANT: pittura a blocchi e piani con pennellata rettangolare + luci speculari (stile Sargent)." },
  { type: "tools/art/carboncino", category: "art", glyph: "CRB", shortLabel: "Carbon", tooltip: "CARBONCINO: disegno a tratti e scumble in 3 passate con controlli upscale/densita/pressione." },
  { type: "tools/art/crosshatch-bn", category: "art", glyph: "XHB", shortLabel: "XH BN", tooltip: "CROSSHATCH BN: line art b/n multi-angolo (0-90) con output raster + SVG." },
  { type: "tools/art/matita", category: "art", glyph: "MAT", shortLabel: "Matita", tooltip: "MATITA: single-line painter ottimizzato con passate, semplificazione RDP e output raster + SVG." },
  { type: "tools/plotter/boxes", category: "plotter", glyph: "PBX", shortLabel: "Boxes", tooltip: "PLOTTER/BOXES: box-grid derivata da tools/plotter/legacy/boxes.js con parametri legacy completi." },
  { type: "tools/plotter/delaunay", category: "plotter", glyph: "PDE", shortLabel: "Delaunay", tooltip: "PLOTTER/DELAUNAY: triangolazione con stipple iterativo, spread e gamma da tools/plotter/legacy/delaunay.js." },
  { type: "tools/plotter/dots", category: "plotter", glyph: "PDT", shortLabel: "Dots", tooltip: "PLOTTER/DOTS: punteggiatura lineare con direction random/seed da tools/plotter/legacy/dots.js." },
  { type: "tools/plotter/halftone", category: "plotter", glyph: "PHF", shortLabel: "Halftone", tooltip: "PLOTTER/HALFTONE: retino cerchi/diamanti con divisions/factor/cutoff da tools/plotter/legacy/halftone.js." },
  { type: "tools/plotter/implode", category: "plotter", glyph: "PIM", shortLabel: "Implode", tooltip: "PLOTTER/IMPLODE: raggi centripeti con threshold, dither e route optimize da tools/plotter/legacy/implode.js." },
  { type: "tools/plotter/jaggy", category: "plotter", glyph: "PJG", shortLabel: "Jaggy", tooltip: "PLOTTER/JAGGY: single-path jagged con seed, derivato da tools/plotter/legacy/jaggy.js." },
  { type: "tools/plotter/linedraw", category: "plotter", glyph: "PLD", shortLabel: "Linedraw", tooltip: "PLOTTER/LINEDRAW: contour/hatching/noise-scale da tools/plotter/legacy/linedraw.js." },
  { type: "tools/plotter/linescan", category: "plotter", glyph: "PLS", shortLabel: "Linescan", tooltip: "PLOTTER/LINESCAN: scansione threshold su assi horizontal/vertical/both da tools/plotter/legacy/linescan.js." },
  { type: "tools/plotter/longwave", category: "plotter", glyph: "PLW", shortLabel: "Longwave", tooltip: "PLOTTER/LONGWAVE: onde lunghe con depth/direction/simplify da tools/plotter/legacy/longwave.js." },
  { type: "tools/plotter/mosaic", category: "plotter", glyph: "PMO", shortLabel: "Mosaic", tooltip: "PLOTTER/MOSAIC: mosaico hatch con scale/hatches/outlines da tools/plotter/legacy/mosaic.js." },
  { type: "tools/plotter/needles", category: "plotter", glyph: "PND", shortLabel: "Needles", tooltip: "PLOTTER/NEEDLES: needle strokes con max length/threshold da tools/plotter/legacy/needles.js." },
  { type: "tools/plotter/peano", category: "plotter", glyph: "PPE", shortLabel: "Peano", tooltip: "PLOTTER/PEANO: spazio riempiente con order/hblocks/vblocks da tools/plotter/legacy/peano.js." },
  { type: "tools/plotter/polyspiral", category: "plotter", glyph: "PPS", shortLabel: "PolySp", tooltip: "PLOTTER/POLYSPIRAL: spirale poligonale con polygon/frequency/amplitude/spacing da tools/plotter/legacy/polyspiral.js." },
  { type: "tools/plotter/sawtooth", category: "plotter", glyph: "PSW", shortLabel: "Saw", tooltip: "PLOTTER/SAWTOOTH: sawtooth linework con lineCount/sampling da tools/plotter/legacy/sawtooth.js." },
  { type: "tools/plotter/spiral", category: "plotter", glyph: "PSP", shortLabel: "Spiral", tooltip: "PLOTTER/SPIRAL: spirale radiale con frequency/amplitude/spacing da tools/plotter/legacy/spiral.js." },
  { type: "tools/plotter/springs", category: "plotter", glyph: "PSR", shortLabel: "Springs", tooltip: "PLOTTER/SPRINGS: pattern a molla con widdershins da tools/plotter/legacy/springs.js." },
  { type: "tools/plotter/squiggle", category: "plotter", glyph: "PSQ", shortLabel: "Squig", tooltip: "PLOTTER/SQUIGGLE: squiggle classico con modulazione AM/FM/BOTH da tools/plotter/legacy/squiggle.js." },
  { type: "tools/plotter/squiggle-left-right", category: "plotter", glyph: "PSL", shortLabel: "Sq L/R", tooltip: "PLOTTER/SQUIGGLE L/R: zig-zag left-right con join-ends da tools/plotter/legacy/squiggleLeftRight.js." },
  { type: "tools/plotter/stipple", category: "plotter", glyph: "PST", shortLabel: "Stipple", tooltip: "PLOTTER/STIPPLE: voronoi stippling con TSP art e shape modes da tools/plotter/legacy/stipple.js." },
  { type: "tools/plotter/subline", category: "plotter", glyph: "PSU", shortLabel: "Subline", tooltip: "PLOTTER/SUBLINE: subline multilineari con sublines/amplitude/sampling da tools/plotter/legacy/subline.js." },
  { type: "tools/plotter/waves", category: "plotter", glyph: "PWV", shortLabel: "Waves", tooltip: "PLOTTER/WAVES: onde orientate per angle/step-size da tools/plotter/legacy/waves.js." },
  { type: "tools/plotter/woven", category: "plotter", glyph: "PWO", shortLabel: "Woven", tooltip: "PLOTTER/WOVEN: effetto tessuto con cosine/random/power da tools/plotter/legacy/woven.js." },
  { type: "tools/svg/rough", category: "svg", glyph: "RFX", shortLabel: "Rough", tooltip: "ROUGH: applica stile rough a un SVG in ingresso e produce un nuovo SVG." },
  { type: "tools/svg/svg-simplify", category: "svg", glyph: "SMP", shortLabel: "Simplify", tooltip: "SVG SIMPLIFY: semplifica path e minifica SVG riducendo il peso mantenendo i colori." },
  { type: "tools/ai/bg-remove", category: "ai", glyph: "BGR", shortLabel: "BG Remove", tooltip: "BG REMOVE: rimuove lo sfondo con segmentazione persona AI (stile MediaPipe/selfie segmentation)." },
  { type: "tools/ai/pose-detect", category: "ai", glyph: "POS", shortLabel: "Pose", tooltip: "POSE DETECT: rilevamento posa persona con box testa/torso/arti/collo/piedi (stile MoveNet tfjs)." },
  { type: "tools/ai/face-landmarker", category: "ai", glyph: "FLC", shortLabel: "Face LM", tooltip: "FACE LANDMARKER: rileva mesh, occhi, labbra, iridi e blendshapes del volto (MediaPipe)." },
  { type: "tools/ai/ml5-extract", category: "ai", glyph: "ML5", shortLabel: "ML5", tooltip: "ML5 EXTRACT: estrae bodypose/handpose/facemesh/imageclassifier (se disponibile) da un'immagine." },
  { type: "output/image", category: "io", glyph: "OUT", shortLabel: "Output", tooltip: "OUTPUT: mostra il risultato finale e permette il download." },
  { type: "output/palette", category: "colors", glyph: "PAL", shortLabel: "Palette", tooltip: "PALETTE: visualizza e salva i colori in ingresso." },
  { type: "output/svg", category: "io", glyph: "S/O", shortLabel: "SVG Out", tooltip: "SVG OUTPUT: mostra un SVG in input e permette il download." },
  { type: "output/ml5", category: "io", glyph: "J/O", shortLabel: "JSON Out", tooltip: "JSON OUTPUT: mostra i dati in formato JSON e permette il download." },
  { type: "output/txt", category: "io", glyph: "T/O", shortLabel: "TXT Out", tooltip: "TXT OUTPUT: mostra testo in font fisso 8pt e permette il download .txt." },
];
